baseURL = "https://entropy-garden.net/"
title = "Entropy Garden"
theme = "PaperMod"
languageCode = "en-us"

defaultContentLanguage = "en"

[pagination]
pagerSize = 10

[languages]

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1

[languages.ru]
contentDir = "content/ru"
languageName = "Русский"
weight = 2

[params]
defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true


[languages.en.menu]

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20


[languages.ru.menu]

[[languages.ru.menu.main]]
identifier = "about"
name = "Обо мне"
url = "/about/"
weight = 10

[[languages.ru.menu.main]]
identifier = "posts"
name = "Проекты"
url = "/posts/"
weight = 20



